var DATA = [
      { id:0, label:"org.nnsoft.commons.meiyo.classpath", link:"org/nnsoft/commons/meiyo/classpath/package-summary.html", type:"package" },
      { id:1, label:"org.nnsoft.commons.meiyo.classpath.AbstractHandlerConfiguration", link:"org/nnsoft/commons/meiyo/classpath/AbstractHandlerConfiguration.html", type:"class" },
      { id:2, label:"org.nnsoft.commons.meiyo.classpath.ClassLoaderBuilder", link:"org/nnsoft/commons/meiyo/classpath/ClassLoaderBuilder.html", type:"class" },
      { id:3, label:"org.nnsoft.commons.meiyo.classpath.ClassPathEntryHandler", link:"org/nnsoft/commons/meiyo/classpath/ClassPathEntryHandler.html", type:"class" },
      { id:4, label:"org.nnsoft.commons.meiyo.classpath.ErrorHandler", link:"org/nnsoft/commons/meiyo/classpath/ErrorHandler.html", type:"class" },
      { id:5, label:"org.nnsoft.commons.meiyo.classpath.ErrorHandlerBuilder", link:"org/nnsoft/commons/meiyo/classpath/ErrorHandlerBuilder.html", type:"class" },
      { id:6, label:"org.nnsoft.commons.meiyo.classpath.HandlerConfiguration", link:"org/nnsoft/commons/meiyo/classpath/HandlerConfiguration.html", type:"class" },
      { id:7, label:"org.nnsoft.commons.meiyo.classpath.HandlerConfigurationsBuilder", link:"org/nnsoft/commons/meiyo/classpath/HandlerConfigurationsBuilder.html", type:"class" },
      { id:8, label:"org.nnsoft.commons.meiyo.classpath.LinkedHandlerBuilder", link:"org/nnsoft/commons/meiyo/classpath/LinkedHandlerBuilder.html", type:"class" },
      { id:9, label:"org.nnsoft.commons.meiyo.classpath.Matcher", link:"org/nnsoft/commons/meiyo/classpath/Matcher.html", type:"class" },
      { id:10, label:"org.nnsoft.commons.meiyo.classpath.MeiyoScanner", link:"org/nnsoft/commons/meiyo/classpath/MeiyoScanner.html", type:"class" },
      { id:11, label:"org.nnsoft.commons.meiyo.classpath.filter", link:"org/nnsoft/commons/meiyo/classpath/filter/package-summary.html", type:"package" },
      { id:12, label:"org.nnsoft.commons.meiyo.classpath.filter.Filter", link:"org/nnsoft/commons/meiyo/classpath/filter/Filter.html", type:"class" },
      { id:13, label:"org.nnsoft.commons.meiyo.classpath.filter.Filters", link:"org/nnsoft/commons/meiyo/classpath/filter/Filters.html", type:"class" },
      { id:14, label:"org.nnsoft.commons.meiyo.classvisitor", link:"org/nnsoft/commons/meiyo/classvisitor/package-summary.html", type:"package" },
      { id:15, label:"org.nnsoft.commons.meiyo.classvisitor.AbstractVisitorConfiguration", link:"org/nnsoft/commons/meiyo/classvisitor/AbstractVisitorConfiguration.html", type:"class" },
      { id:16, label:"org.nnsoft.commons.meiyo.classvisitor.AnnotatedHandlerBuilder", link:"org/nnsoft/commons/meiyo/classvisitor/AnnotatedHandlerBuilder.html", type:"class" },
      { id:17, label:"org.nnsoft.commons.meiyo.classvisitor.AnnotationHandler", link:"org/nnsoft/commons/meiyo/classvisitor/AnnotationHandler.html", type:"class" },
      { id:18, label:"org.nnsoft.commons.meiyo.classvisitor.AnnotationHandlerBinder", link:"org/nnsoft/commons/meiyo/classvisitor/AnnotationHandlerBinder.html", type:"class" },
      { id:19, label:"org.nnsoft.commons.meiyo.classvisitor.ClassVisitor", link:"org/nnsoft/commons/meiyo/classvisitor/ClassVisitor.html", type:"class" },
      { id:20, label:"org.nnsoft.commons.meiyo.classvisitor.LinkedHandlingBuilder", link:"org/nnsoft/commons/meiyo/classvisitor/LinkedHandlingBuilder.html", type:"class" },
      { id:21, label:"org.nnsoft.commons.meiyo.classvisitor.MeiyoVisitor", link:"org/nnsoft/commons/meiyo/classvisitor/MeiyoVisitor.html", type:"class" },
      { id:22, label:"org.nnsoft.commons.meiyo.classvisitor.VisitorConfiguration", link:"org/nnsoft/commons/meiyo/classvisitor/VisitorConfiguration.html", type:"class" }

    ];
